# Generated by Django 3.0.14 on 2022-08-03 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='time',
            new_name='time_utc',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='event',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='selection_description',
        ),
        migrations.AddField(
            model_name='tip',
            name='league',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='match_clock',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='playera',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='playerb',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='market',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='selection',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='users',
            field=models.ManyToManyField(null=True, through='app.UserTipped', to=settings.AUTH_USER_MODEL),
        ),
    ]
