# Generated by Django 3.0.14 on 2022-08-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220803_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tip',
            name='match_clock',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tippingstrategy',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
