# Generated by Django 3.0.14 on 2022-08-04 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220803_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='users',
            field=models.ManyToManyField(through='app.UserTipped', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertipped',
            name='odds_bet',
            field=models.FloatField(null=True),
        ),
    ]
