# Generated by Django 3.0.14 on 2022-08-04 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220804_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertipped',
            name='odds_bet',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='usertipped',
            name='stake_bet',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
