# Generated by Django 3.0.14 on 2022-08-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220804_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='time_utc',
            new_name='time',
        ),
        migrations.AddField(
            model_name='usertipped',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
