# Generated by Django 3.0.14 on 2022-08-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220820_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bettingaccount',
            old_name='betting_account',
            new_name='name',
        ),
    ]
