# Generated by Django 3.0.14 on 2022-08-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220821_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banter_status',
            field=models.BooleanField(default=True),
        ),
    ]
