# Generated by Django 3.0.14 on 2022-08-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_banter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='banter_status',
        ),
    ]
